services:
  mongo_db:
    container_name: di_container
    image: mongo:5.0.5
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: di_db
      MONGO_INITDB_USERNAME: di_admin
      MONGO_INITDB_PASSWORD: di_admin_pwd
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/mongo-init.js:ro