mongodb:
  host: 127.0.0.1:27017
  database: di_db
  username: di_admin
  password: di_admin_pwd

ftp:
  server: localhost
  port: 21
  user_name: admin
  password: Abc12345

cors:
  allow_origins:
    - 'http://localhost:3000'
  allow_methods:
    - PUT
    - PATCH
    - GET
    - POST
    - DELETE
    - OPTIONS