mongodb:
  host: 127.0.0.1:27017
  database: di_db
  username: di_admin
  password: di_admin_pwd

ftp:
  server: jpro2.jpo.or.jp
  port: 21
  user_name: vj_kinkan@receive
  password: 03-3294-7652

cors:
  allow_origins:
    - 'https://prod.app'
  allow_methods:
    - PUT
    - PATCH
    - GET
    - POST
    - DELETE
    - OPTIONS